<a href="https://colab.research.google.com/github/pacd321/ML/blob/main/NumPy(Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python


In [8]:
import numpy as np

In [15]:
from time import process_time

In [16]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007820950000017035


In [18]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array =+ 5

end_time = process_time()

print(end_time - start_time)

0.00013011899999781917


In [20]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [21]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [23]:
#creating a 1D array
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [24]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [25]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype =float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [29]:
#create a numpy array of Zeros
x = np.zeros((5,5),dtype =int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [30]:
#create a numpy array of Ones
y = np.ones((3,3) , dtype = int)
print(y)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [34]:
#create a numpy array of particular value
z = np.full((5,4),10)
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [37]:
#create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
#create a numpy array with random value
b = np.random.random((3,4))
print(b)

[[0.78233386 0.31747762 0.52337246 0.26368943]
 [0.92988415 0.99887959 0.36511523 0.70776899]
 [0.32828198 0.34935932 0.98545795 0.74896245]]


In [46]:
#random integer values in the matrix
c = np.random.randint(10,100,(3,5))
print(c)

[[66 69 58 58 44]
 [84 37 20 70 29]
 [36 82 75 20 70]]


In [50]:
#array of evenly spaced values
d = np.linspace(10,30,6,dtype=int)
print(d)

[10 14 18 22 26 30]


In [54]:
#array of evenely spaced values specifying the steps
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [55]:
#convert a list to numpy array
list2 = [10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [57]:
#Analysing an array
c = np.random.randint(10,50,(5,5))
print(c)

[[22 45 13 44 35]
 [49 49 48 48 27]
 [18 15 29 45 22]
 [21 22 30 36 28]
 [41 16 19 30 10]]


In [58]:
print(c.shape)

(5, 5)


In [59]:
#number of dimensions
print(c.ndim)

2


In [60]:
#number of elements in an array
print(c.size)

25


In [61]:
#checking datatype
print(c.dtype)

int64


Mathmatical operations on NumPy

In [62]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # + sign will concatentate

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [70]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.subtract(a,b))

[[19 20 17]
 [12 13 13]
 [16 16 18]]
[[18 75 52]
 [11 30 12]
 [15 15 65]]
[[0.05555556 0.33333333 0.30769231]
 [0.09090909 0.3        0.08333333]
 [0.06666667 0.06666667 0.38461538]]
[[-17 -10  -9]
 [-10  -7 -11]
 [-14 -14  -8]]


In [83]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)


[[1 7 9]
 [0 5 8]]
(2, 3)


In [84]:
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 0]
 [7 5]
 [9 8]]
(3, 2)


In [86]:
b = array.reshape(3,2)
print(b)

[[1 7]
 [9 0]
 [5 8]]
